#!/bin/bash

#Created by Chris Mariano

#Switch to the /tmp directory
cd /tmp

#Download the Trend installer
curl -O -k https://y5vpnu.manage.trendmicro.com:443/officescan/console/html/TMSM_HTML/ActiveUpdate/ClientInstall/tmsminstall.zip

#Unzip the installer
unzip tmsminstall.zip

#Install the Trend Software
installer -pkg /private/tmp/tmsmuninstall/tmsmuninstall.pkg -target /
installer -pkg /tmp/tmsminstall/tmsminstall.pkg -target /
rm tmsminstall.zip
rm -rf /tmp/tmsminstall

exit 0
